name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "v*"

jobs:
  # ---
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Linting
        run: pipx run hatch fmt --check

      - name: Unit Tests
        run: pipx run hatch test
  # ---
  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Check Build
        run: pipx run hatch -v build

